services:
  openvpn:
    container_name: openvpn
    build: ./openvpn-docker
    ports:
      - "1194:1194/udp"
    networks:
      vpn-net:
        ipv4_address: 172.20.0.3
    volumes:
      - ./openvpn/pki:/etc/openvpn/pki
      - ./openvpn/clients:/etc/openvpn/clients
      - ./openvpn/config:/etc/openvpn/config
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    devices:
      - /dev/net/tun

  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - "openvpn"
    networks:
      vpn-net:
        ipv4_address: 172.20.0.2
    environment:
      TZ: "Asia/Hong_Kong"
      FTLCONF_webserver_api_password: "password"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "1.1.1.1;8.8.8.8" # Cloudflare and Google
    volumes:
      - './pihole/pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  vpn-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

