services:
  openvpn:
    container_name: openvpn
    build: ./openvpn-docker
    network_mode: host
    volumes:
      - ./openvpn/pki:/etc/openvpn/pki
      - ./openvpn/clients:/etc/openvpn/clients
      - ./openvpn/config:/etc/openvpn/config
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    devices:
      - /dev/net/tun

  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - "openvpn"
    network_mode: host
    environment:
      TZ: "Asia/Hong_Kong"
      FTLCONF_webserver_api_password: "password"
      FTLCONF_dns_listeningMode: "all"
      FTLCONF_dns_upstreams: "208.67.222.222;208.67.220.220" # OpenDNS
    volumes:
      - './pihole/pihole:/etc/pihole'
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.05'
          memory: 10M
    restart: unless-stopped
